version: '2'
services:
  appliance-snmp1:
    build:
      context: ./
    image: com.ymagis.emulator/applitmp
    ports:
          - "161:161/udp"
    networks:
         myvlan:
             ipv4_address: 192.168.0.92
            
#  appliance-snmp2:
#    build:
#      context: ./
#    image: com.ymagis.emulator/applitmp
#    ports:
#          - "161:161/udp"
#    networks:
#         myvlan:
#             ipv4_address: 192.168.0.93
 

networks:
  myvlan:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.92/28
#          aux-address:
#            host: 192.168.1.223